# Generated by Django 5.1 on 2024-08-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
