# Generated by Django 5.1.1 on 2024-09-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_views_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=150, verbose_name='слаг')),
                ('content', models.TextField(verbose_name='содержание')),
                ('preview_image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('views_counter', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
            ],
        ),
    ]
