# Generated by Django 5.1.1 on 2024-09-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_description'),
        ('catalog', '0007_blogarticle'),
    ]

    operations = []
