# Generated by Django 5.1.1 on 2024-09-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_views_counter'),
    ]

    operations = []
