# Generated by Django 5.1.1 on 2024-09-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_description'),
        ('catalog', '0007_blogarticle'),
        ('catalog', '0009_alter_blogarticle_options_alter_product_description_and_more'),
    ]

    operations = [
    ]
